# Generated by Django 4.0.4 on 2022-04-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/ingresos/')),
                ('ingreso', models.DateTimeField(blank=True, null=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_empleado', to='empleado.empleado')),
            ],
        ),
    ]
